//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 06:58:06 PM CEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAuthorsRequest_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "getAuthorsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemoveBookRequest }
     * 
     */
    public RemoveBookRequest createRemoveBookRequest() {
        return new RemoveBookRequest();
    }

    /**
     * Create an instance of {@link AuthenticatedRequest }
     * 
     */
    public AuthenticatedRequest createAuthenticatedRequest() {
        return new AuthenticatedRequest();
    }

    /**
     * Create an instance of {@link GetBookResponse }
     * 
     */
    public GetBookResponse createGetBookResponse() {
        return new GetBookResponse();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link BookResponse }
     * 
     */
    public BookResponse createBookResponse() {
        return new BookResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link AccountResponse }
     * 
     */
    public AccountResponse createAccountResponse() {
        return new AccountResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link EditAccountRequest }
     * 
     */
    public EditAccountRequest createEditAccountRequest() {
        return new EditAccountRequest();
    }

    /**
     * Create an instance of {@link AccountRequest }
     * 
     */
    public AccountRequest createAccountRequest() {
        return new AccountRequest();
    }

    /**
     * Create an instance of {@link GetBooksRequest }
     * 
     */
    public GetBooksRequest createGetBooksRequest() {
        return new GetBooksRequest();
    }

    /**
     * Create an instance of {@link BookBookRequest }
     * 
     */
    public BookBookRequest createBookBookRequest() {
        return new BookBookRequest();
    }

    /**
     * Create an instance of {@link SetUserRoleRequest }
     * 
     */
    public SetUserRoleRequest createSetUserRoleRequest() {
        return new SetUserRoleRequest();
    }

    /**
     * Create an instance of {@link GetAuthorsResponse }
     * 
     */
    public GetAuthorsResponse createGetAuthorsResponse() {
        return new GetAuthorsResponse();
    }

    /**
     * Create an instance of {@link AuthorResponse }
     * 
     */
    public AuthorResponse createAuthorResponse() {
        return new AuthorResponse();
    }

    /**
     * Create an instance of {@link GetBooksResponse }
     * 
     */
    public GetBooksResponse createGetBooksResponse() {
        return new GetBooksResponse();
    }

    /**
     * Create an instance of {@link BorrowBookRequest }
     * 
     */
    public BorrowBookRequest createBorrowBookRequest() {
        return new BorrowBookRequest();
    }

    /**
     * Create an instance of {@link CreateAccountRequest }
     * 
     */
    public CreateAccountRequest createCreateAccountRequest() {
        return new CreateAccountRequest();
    }

    /**
     * Create an instance of {@link CancelBookingRequest }
     * 
     */
    public CancelBookingRequest createCancelBookingRequest() {
        return new CancelBookingRequest();
    }

    /**
     * Create an instance of {@link AddBookRequest }
     * 
     */
    public AddBookRequest createAddBookRequest() {
        return new AddBookRequest();
    }

    /**
     * Create an instance of {@link GetBookRequest }
     * 
     */
    public GetBookRequest createGetBookRequest() {
        return new GetBookRequest();
    }

    /**
     * Create an instance of {@link ReturnBookRequest }
     * 
     */
    public ReturnBookRequest createReturnBookRequest() {
        return new ReturnBookRequest();
    }

    /**
     * Create an instance of {@link IdResponse }
     * 
     */
    public IdResponse createIdResponse() {
        return new IdResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://spring.io/guides/gs-producing-web-service", name = "getAuthorsRequest")
    public JAXBElement<Object> createGetAuthorsRequest(Object value) {
        return new JAXBElement<Object>(_GetAuthorsRequest_QNAME, Object.class, null, value);
    }

}
